### ISSUE TITLE
Movie tiling acts weird

### ISSUE THREAD

**Issue by davidv1992** [privacybydesign/irmatube#1]
The number of columns used to display the movies is inconsistent between various screensizes and leaves whitespace between last film and register button, which is less than ideal

**Comment by ivard** [comment]
Indeed the number of columns is different, but I don't see problems with the 'Register' button as it is on the top of the page. The only thing that is a bit ugly is the line break in 'IRMATube is the privacy-friendly video-streaming service'. However if I fix this, it is ugly again on bigger screens. I tried some different settings, but I wasn't able to find a quick way to do it better. Was this the issue you meant?

![image](https://user-images.githubusercontent.com/17035191/63272470-65caff80-c29c-11e9-8bf7-814ec8b9bc22.png)
